prod:
  image: vizzuality/gee-analysis-gee:1.1.0${STAGING}
  ports:
    - "4500"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: gee-analysis-gee${STAGING}
